# Generated by Django 3.2.7 on 2021-09-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
