# Generated by Django 3.2.7 on 2021-09-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_slider_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
